# Generated by Django 5.2.15 on 2026-07-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='attributes.attribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'attribute')},
            },
        ),
    ]
